---

- name: "Install Docker on AWS EC2 Instance" 
  hosts: all
  become: true
  tasks:
    - name: Show facts available on the system
      ansible.builtin.debug:
        var: ansible_facts

    - name: update all package
      yum: 
        name: '*'
        state: latest
        update_only: yes

    - name: Install the required dependencies
      yum:
        name: "{{ packages }}"
        state: latest
        update_cache: yes
      vars:
        packages:
        - python-pip
        - yum-utils
        - device-mapper-persistent-data
        - lvm2
        - amazon-linux-extras


    - name: Install docker-ce via amazon-linux-extra-packages
      shell: "amazon-linux-extras enable python3.8 ansible2 docker"

    - name: Clean yum metadata cache
      command: yum clean metadata
      args:
        warn: false

    - name: Ensure a list of yum packages are installed
      yum:
        name: "{{ packages }}"
        state: latest
        update_cache: yes
      vars:
        packages:
        - python3.8
        - ansible
        - docker
  

    - name: Enable Docker CE service at start up
      service:
        name: docker
        state: started
        enabled: yes

    - name: Upgrade pip3
      shell: "python3.8 -m pip install pip --upgrade"

    - name: Ensure python pip packages are installed
      pip:
       name: "{{ packages }}"
       executable: /usr/local/bin/pip3.8
      vars:
        packages:
        - boto
        - boto3
        - docker-compose


