---

- hosts: all
  become: true
  vars_files:
   - vars/vars.yaml
  tasks:
  #- debug:
  #  var: ansible_os_family
 

  - name: Show facts available on the system
    ansible.builtin.debug:
      var: ansible_facts

  - name: "create yum repository for docker"
    yum_repository:
      name: docker-repo
      description: "Repo for docker"
      baseurl: "https://download.docker.com/linux/centos/7/x86_64/stable/"
      enabled: yes
      repo_gpgcheck: no
    when: ansible_facts['os_family'] == 'RedHat'

  - name: Install Docker
    yum:
      name: '{{ item }}'
      state: present
    loop:
      - slirp4netns
      - container-selinux
      - fuse-overlayfs

  - name: Install Pip
    yum:
      name: "python3-pip"
      state: present
      update_cache: true


